"use strict";

const os = require('os');

/**
* See errors table https://www-numi.fnal.gov/offline_software/srt_public_context/WebDocs/Errors/unix_system_errors.html
*/


// same on unix + windows
const commons = {
  EPERM    : -1,
  ENOENT   : -2,
  ESRCH    : -3,
  EINTR    : -4,
  EIO      : -5,
  ENXIO    : -6,
  E2BIG    : -7,
  ENOEXEC  : -8,
  EBADF    : -9,
  ECHILD   : -10,
  EAGAIN   : -11,
  ENOMEM   : -12,
  EACCES   : -13,
  EFAULT   : -14,
  EBUSY    : -16,
  EEXIST   : -17,
  EXDEV    : -18,
  ENODEV   : -19,
  ENOTDIR  : -20,
  EISDIR   : -21,
  EINVAL   : -22,
  ENFILE   : -23,
  EMFILE   : -24,
  ENOTTY   : -25,
  EFBIG    : -27,
  ENOSPC   : -28,
  ESPIPE   : -29,
  EROFS    : -30,
  EMLINK   : -31,
  EPIPE    : -32,
  EDOM     : -33,
  ERANGE   : -34,
};

const notwin = {
  ENOTBLK        : -15,
  ETXTBSY        : -26,
  EDEADLK        : -35,
  ENAMETOOLONG   : -36,
  ENOLCK         : -37,
  ENOSYS         : -38,
  ENOTEMPTY      : -39,
  ELOOP          : -40,
  EWOULDBLOCK    : -11,
  ENOMSG         : -42,
  EIDRM          : -43,
  ECHRNG         : -44,
  EL2NSYNC       : -45,
  EL3HLT         : -46,
  EL3RST         : -47,
  ELNRNG         : -48,
  EUNATCH        : -49,
  ENOCSI         : -50,
  EL2HLT         : -51,
  EBADE          : -52,
  EBADR          : -53,
  EXFULL         : -54,
  ENOANO         : -55,
  EBADRQC        : -56,
  EBADSLT        : -57,
  EDEADLOCK      : -35,
  EBFONT         : -59,
  ENOSTR         : -60,
  ENODATA        : -61,
  ETIME          : -62,
  ENOSR          : -63,
  ENONET         : -64,
  ENOPKG         : -65,
  EREMOTE        : -66,
  ENOLINK        : -67,
  EADV           : -68,
  ESRMNT         : -69,
  ECOMM          : -70,
  EPROTO         : -71,
  EMULTIHOP      : -72,
  EDOTDOT        : -73,
  EBADMSG        : -74,
  EOVERFLOW      : -75,
  ENOTUNIQ       : -76,
  EBADFD         : -77,
  EREMCHG        : -78,
  ELIBACC        : -79,
  ELIBBAD        : -80,
  ELIBSCN        : -81,
  ELIBMAX        : -82,
  ELIBEXEC       : -83,
  EILSEQ         : -84,
  ERESTART       : -85,
  ESTRPIPE       : -86,
  EUSERS         : -87,
  ENOTSOCK       : -88,
  EDESTADDRREQ   : -89,
  EMSGSIZE       : -90,
  EPROTOTYPE     : -91,
  ENOPROTOOPT    : -92,
  EPROTONOSUPPORT : -93,
  ESOCKTNOSUPPORT : -94,
  EOPNOTSUPP     : -95,
  EPFNOSUPPORT   : -96,
  EAFNOSUPPORT   : -97,
  EADDRINUSE     : -98,
  EADDRNOTAVAIL  : -99,
  ENETDOWN       : -100,
  ENETUNREACH    : -101,
  ENETRESET      : -102,
  ECONNABORTED   : -103,
  ECONNRESET     : -104,
  ENOBUFS        : -105,
  EISCONN        : -106,
  ENOTCONN       : -107,
  ESHUTDOWN      : -108,
  ETOOMANYREFS   : -109,
  ETIMEDOUT      : -110,
  ECONNREFUSED   : -111,
  EHOSTDOWN      : -112,
  EHOSTUNREACH   : -113,
  EALREADY       : -114,
  EINPROGRESS    : -115,
  ESTALE         : -116,
  EUCLEAN        : -117,
  ENOTNAM        : -118,
  ENAVAIL        : -119,
  EISNAM         : -120,
  EREMOTEIO      : -121,
  EDQUOT         : -122,
  ENOMEDIUM      : -123,
  EMEDIUMTYPE    : -124,
};

const win = {
  ETXTBSY        : -139,
  EDEADLK        : -36,
  ENAMETOOLONG   : -38,
  ENOLCK         : -39,
  ENOSYS         : -40,
  ENOTEMPTY      : -41,
  ELOOP          : -114,
  EWOULDBLOCK    : -140,
  ENOMSG         : -122,
  EIDRM          : -111,
  EDEADLOCK      : -36,
  ENOSTR         : -125,
  ENODATA        : -120,
  ETIME          : -137,
  ENOSR          : -124,
  ENOLINK        : -121,
  EPROTO         : -134,
  EBADMSG        : -104,
  EOVERFLOW      : -132,
  EBADFD         : -9,
  EILSEQ         : -42,
  ENOTSOCK       : -128,
  EDESTADDRREQ   : -109,
  EMSGSIZE       : -115,
  EPROTOTYPE     : -136,
  ENOPROTOOPT    : -123,
  EPROTONOSUPPORT : -135,
  EOPNOTSUPP     : -130,
  EAFNOSUPPORT   : -102,
  EADDRINUSE     : -100,
  EADDRNOTAVAIL  : -101,
  ENETDOWN       : -116,
  ENETUNREACH    : -118,
  ENETRESET      : -117,
  ECONNABORTED   : -106,
  ECONNRESET     : -108,
  ENOBUFS        : -119,
  EISCONN        : -113,
  ENOTCONN       : -126,
  ETIMEDOUT      : -138,
  ECONNREFUSED   : -107,
  EHOSTUNREACH   : -110,
  EALREADY       : -103,
  EINPROGRESS    : -112,
};


const codes = {...commons, ...(os.platform() !== 'win32' ? notwin : win)};

module.exports = codes;
