name: tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - run: sudo apt-get install -qq fuse libfuse-dev
    - run: sudo modprobe fuse
    - run: sudo chmod 666 /dev/fuse
    - run: sudo chown root:$USER /etc/fuse.conf
    - run: echo "user_allow_other" | sudo tee /etc/fuse.conf
    - run: fusermount -V

    - run: npm install
    - run: npm test
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}